name       : libdmtx
version    : 0.7.5
release    : 2
source     :
    - https://github.com/dmtx/libdmtx/archive/refs/tags/v0.7.5.tar.gz : be0c5275695a732a5f434ded1fcc232aa63b1a6015c00044fe87f3a689b75f2e
homepage   : https://github.com/dmtx/libdmtx
license    : BSD-2-Clause
component  : programming.library
summary    : Library to read and write Data Matrix barcodes
description: |
    libdmtx is a software library that enables programs to read and write Data Matrix barcodes of the modern ECC200 variety. The library runs natively on several platforms and can be accessed by multiple languages using the libdmtx language wrappers. The utility programs dmtxread and dmtxwrite also provide a command line interface for libdmtx, and serve as a good reference for developers writing their own libdmtx-enabled programs.
setup      : |
    %apply_patches
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
