name       : libdmtx
version    : 0.7.7
release    : 3
source     :
    - https://github.com/dmtx/libdmtx/archive/refs/tags/v0.7.7.tar.gz : 7aa62adcefdd6e24bdabeb82b3ce41a8d35f4a0c95ab0c4438206aecafd6e1a1
homepage   : https://github.com/dmtx/libdmtx
license    : BSD-2-Clause
component  : programming.library
summary    : Library to read and write Data Matrix barcodes
description: |
    libdmtx is a software library that enables programs to read and write Data Matrix barcodes of the modern ECC200 variety. The library runs natively on several platforms and can be accessed by multiple languages using the libdmtx language wrappers. The utility programs dmtxread and dmtxwrite also provide a command line interface for libdmtx, and serve as a good reference for developers writing their own libdmtx-enabled programs.
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
